[2022-09-16T23:32:46.447+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2022-09-16T23:32:38.353246+00:00 [queued]>
[2022-09-16T23:32:46.473+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2022-09-16T23:32:38.353246+00:00 [queued]>
[2022-09-16T23:32:46.479+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-16T23:32:46.480+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2022-09-16T23:32:46.481+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-16T23:32:46.505+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-09-16 23:32:38.353246+00:00
[2022-09-16T23:32:46.522+0000] {standard_task_runner.py:52} INFO - Started process 320 to run task
[2022-09-16T23:32:46.527+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'manual__2022-09-16T23:32:38.353246+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpo9_54kbe', '--error-file', '/tmp/tmpj6eoehyw']
[2022-09-16T23:32:46.532+0000] {standard_task_runner.py:80} INFO - Job 45: Subtask local_to_gcs_task
[2022-09-16T23:32:46.696+0000] {task_command.py:371} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2022-09-16T23:32:38.353246+00:00 [running]> on host 2a91e0997e9b
[2022-09-16T23:32:46.790+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-16T23:32:38.353246+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-16T23:32:38.353246+00:00
[2022-09-16T23:32:47.692+0000] {python.py:173} INFO - Done. Returned value was: None
[2022-09-16T23:32:47.711+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20220916T233238, start_date=20220916T233246, end_date=20220916T233247
[2022-09-16T23:32:47.748+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-16T23:32:47.796+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
